.TH "app_latinka_tl Directory Reference" 3 "Thu Mar 25 2021" "Latinka" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app_latinka_tl Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdarkTheme\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainWindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainWindow\&.h\fP"
.br
.in -1c
