.TH "app_latinka_tl/darkTheme.h" 3 "Thu Mar 25 2021" "Latinka" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app_latinka_tl/darkTheme.h
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QPalette>\fP
.br
\fC#include <QStyleFactory>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QSettings \fBsettings\fP ('HKEY_CURRENT_USER\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Themes\\\\Personalize', QSettings::NativeFormat)"
.br
.ti -1c
.RI "void \fBsetDarkTheme\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void setDarkTheme ()"

.PP
Definition at line 7 of file darkTheme\&.h\&.
.SS "QSettings settings ('HKEY_CURRENT_USER\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Themes\\\\Personalize', QSettings::NativeFormat)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Latinka from the source code\&.
