.TH "Latinka" 3 "Fri Mar 26 2021" "Latinka" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Latinka
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConverter\fP"
.br
.RI "The \fBLatinka::Converter\fP class\&. "
.ti -1c
.RI "struct \fBLetter\fP"
.br
.RI "The \fBLatinka::Letter\fP struct\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAlphabet\fP "
.br
.RI "The Alphabet enum\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLatinka::Alphabet\fP"

.PP
The Alphabet enum\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILatin \fP\fP
.TP
\fB\fICyrillic \fP\fP
.TP
\fB\fISubLetter \fP\fP
.TP
\fB\fIOther \fP\fP
.PP
Definition at line 14 of file latinkaConverter\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Latinka from the source code\&.
