.TH "lib_latinka_tl/include/lib_latinka_tl/latinkaConverter.h" 3 "Wed Apr 7 2021" "Latinka" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_latinka_tl/include/lib_latinka_tl/latinkaConverter.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <list>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLatinka::Converter\fP"
.br
.ti -1c
.RI "struct \fBLatinka::Converter::Letter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBLatinka\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLatinka::Alphabet\fP "
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Latinka from the source code\&.
