.TH "Latinka::Converter" 3 "Thu Mar 25 2021" "Latinka" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Latinka::Converter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <latinkaConverter\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLetter\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::wstring \fBrun\fP (\fBAlphabet\fP from, std::wstring text)"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef \fBLetter::Type\fP \fBLType\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBConverter\fP ()"
.br
.ti -1c
.RI "std::wstring \fBtoWStr\fP (const wchar_t &c) const"
.br
.ti -1c
.RI "void \fBaddLetter\fP (\fBLetter::Type\fP type, std::wstring latinL, std::wstring latinU, std::wstring ukrL, std::wstring ukrU)"
.br
.ti -1c
.RI "\fBLType\fP \fBgetLetterType\fP (const std::wstring &str) const"
.br
.ti -1c
.RI "\fBAlphabet\fP \fBgetLetterAlphabet\fP (const std::wstring &str) const"
.br
.ti -1c
.RI "\fBLType\fP \fBgetLetterType\fP (const wchar_t &l) const"
.br
.ti -1c
.RI "\fBAlphabet\fP \fBgetLetterAlphabet\fP (const wchar_t &l) const"
.br
.ti -1c
.RI "bool \fBisLetterCompareAlphabet\fP (const \fBAlphabet\fP &type, const std::wstring &str) const"
.br
.ti -1c
.RI "bool \fBisLower\fP (const std::wstring &l) const"
.br
.ti -1c
.RI "bool \fBtestSoftLetterWithDoubleEnd\fP (const std::wstring &str) const"
.br
.ti -1c
.RI "std::wstring \fBtoLatin\fP (const std::wstring &letter) const"
.br
.ti -1c
.RI "std::wstring \fBtoUkrajinska\fP (const std::wstring &letter) const"
.br
.ti -1c
.RI "std::wstring \fBtranslitterateWord\fP (const \fBAlphabet\fP &from, std::wstring str) const"
.br
.ti -1c
.RI "std::wstring \fBtranslitterateLetter\fP (const \fBAlphabet\fP &from, const std::wstring &c) const"
.br
.ti -1c
.RI "std::wstring \fBtranslitterateLetter\fP (const \fBAlphabet\fP &from, const std::wstring &c1, const std::wstring &c2) const"
.br
.ti -1c
.RI "std::wstring \fBtranslitterateLetter\fP (const \fBAlphabet\fP &from, const wchar_t &c1, const wchar_t &c2) const"
.br
.ti -1c
.RI "std::wstring \fBtranslitterateLetter\fP (const \fBAlphabet\fP &from, const wchar_t &c) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::list< \fBLetter\fP > \fBm_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file latinkaConverter\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBLetter::Type\fP \fBLatinka::Converter::LType\fP\fC [private]\fP"

.PP
Definition at line 46 of file latinkaConverter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Latinka::Converter::Converter ()\fC [private]\fP"

.PP
Definition at line 22 of file latinkaConverter\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Latinka::Converter::addLetter (\fBLetter::Type\fP type, std::wstring latinL, std::wstring latinU, std::wstring ukrL, std::wstring ukrU)\fC [private]\fP"

.PP
Definition at line 62 of file latinkaConverter\&.cpp\&.
.SS "\fBLatinka::Alphabet\fP Latinka::Converter::getLetterAlphabet (const std::wstring & str) const\fC [private]\fP"

.PP
Definition at line 101 of file latinkaConverter\&.cpp\&.
.SS "\fBLatinka::Alphabet\fP Latinka::Converter::getLetterAlphabet (const wchar_t & l) const\fC [private]\fP"

.PP
Definition at line 120 of file latinkaConverter\&.cpp\&.
.SS "\fBLatinka::Converter::LType\fP Latinka::Converter::getLetterType (const std::wstring & str) const\fC [private]\fP"

.PP
Definition at line 93 of file latinkaConverter\&.cpp\&.
.SS "\fBLatinka::Converter::LType\fP Latinka::Converter::getLetterType (const wchar_t & l) const\fC [private]\fP"

.PP
Definition at line 115 of file latinkaConverter\&.cpp\&.
.SS "bool Latinka::Converter::isLetterCompareAlphabet (const \fBAlphabet\fP & type, const std::wstring & str) const\fC [private]\fP"

.PP
Definition at line 125 of file latinkaConverter\&.cpp\&.
.SS "bool Latinka::Converter::isLower (const std::wstring & l) const\fC [private]\fP"

.PP
Definition at line 132 of file latinkaConverter\&.cpp\&.
.SS "std::wstring Latinka::Converter::run (\fBAlphabet\fP from, std::wstring text)\fC [static]\fP"

.PP
Definition at line 3 of file latinkaConverter\&.cpp\&.
.SS "bool Latinka::Converter::testSoftLetterWithDoubleEnd (const std::wstring & str) const\fC [private]\fP"

.PP
Definition at line 140 of file latinkaConverter\&.cpp\&.
.SS "std::wstring Latinka::Converter::toLatin (const std::wstring & letter) const\fC [private]\fP"

.PP
Definition at line 250 of file latinkaConverter\&.cpp\&.
.SS "std::wstring Latinka::Converter::toUkrajinska (const std::wstring & letter) const\fC [private]\fP"

.PP
Definition at line 262 of file latinkaConverter\&.cpp\&.
.SS "std::wstring Latinka::Converter::toWStr (const wchar_t & c) const\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 150 of file latinkaConverter\&.cpp\&.
.SS "std::wstring Latinka::Converter::translitterateLetter (const \fBAlphabet\fP & from, const std::wstring & c) const\fC [private]\fP"

.PP
Definition at line 243 of file latinkaConverter\&.cpp\&.
.SS "std::wstring Latinka::Converter::translitterateLetter (const \fBAlphabet\fP & from, const std::wstring & c1, const std::wstring & c2) const\fC [private]\fP"

.PP
Definition at line 196 of file latinkaConverter\&.cpp\&.
.SS "std::wstring Latinka::Converter::translitterateLetter (const \fBAlphabet\fP & from, const wchar_t & c) const\fC [private]\fP"

.PP
Definition at line 238 of file latinkaConverter\&.cpp\&.
.SS "std::wstring Latinka::Converter::translitterateLetter (const \fBAlphabet\fP & from, const wchar_t & c1, const wchar_t & c2) const\fC [private]\fP"

.PP
Definition at line 233 of file latinkaConverter\&.cpp\&.
.SS "std::wstring Latinka::Converter::translitterateWord (const \fBAlphabet\fP & from, std::wstring str) const\fC [private]\fP"

.PP
Definition at line 157 of file latinkaConverter\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::list<\fBLetter\fP> Latinka::Converter::m_list\fC [private]\fP"

.PP
Definition at line 52 of file latinkaConverter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Latinka from the source code\&.
