.TH "app_latinka_tl/main.cpp" 3 "Thu Mar 25 2021" "Latinka" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app_latinka_tl/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include <QIcon>\fP
.br
\fC#include 'mainWindow\&.h'\fP
.br
\fC#include 'darkTheme\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 6 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Latinka from the source code\&.
