.TH "app_latinka_tl/mainWindow.h" 3 "Wed Apr 7 2021" "Latinka" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app_latinka_tl/mainWindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets/QTabWidget>\fP
.br
\fC#include <QtWidgets/QLabel>\fP
.br
\fC#include <QtWidgets/QTextEdit>\fP
.br
\fC#include 'lib_latinka_tl/latinkaConverter\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Latinka from the source code\&.
