.TH "app_latinka_tl/mainWindow.cpp" 3 "Thu Mar 25 2021" "Latinka" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app_latinka_tl/mainWindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainWindow\&.h'\fP
.br
\fC#include <QtWidgets>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QPixmap>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Latinka from the source code\&.
